-- CreateTable
CREATE TABLE `project` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `projectName` VARCHAR(191) NOT NULL,
    `clientName` VARCHAR(191) NULL,
    `status` ENUM('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `length` DECIMAL(10, 2) NOT NULL,
    `width` DECIMAL(10, 2) NOT NULL,
    `pitch` DECIMAL(5, 2) NOT NULL,
    `roofType` VARCHAR(191) NOT NULL,
    `floors` INTEGER NOT NULL,
    `materialThickness` VARCHAR(191) NOT NULL,
    `ridgeType` VARCHAR(191) NOT NULL,
    `gutterSize` VARCHAR(191) NOT NULL,
    `budgetLevel` VARCHAR(191) NOT NULL,
    `budgetAmount` DECIMAL(12, 2) NULL,
    `constructionMode` ENUM('NEW', 'REPAIR') NOT NULL DEFAULT 'NEW',
    `gutterLengthA` DECIMAL(10, 2) NULL,
    `gutterSlope` DECIMAL(10, 2) NULL,
    `gutterLengthC` DECIMAL(10, 2) NULL,
    `insulationThickness` VARCHAR(191) NOT NULL,
    `ventilationPieces` INTEGER NOT NULL,
    `material` VARCHAR(191) NOT NULL,
    `area` DECIMAL(10, 2) NOT NULL,
    `materialCost` DECIMAL(12, 2) NOT NULL,
    `gutterCost` DECIMAL(12, 2) NOT NULL,
    `ridgeCost` DECIMAL(12, 2) NOT NULL,
    `screwsCost` DECIMAL(12, 2) NOT NULL,
    `insulationCost` DECIMAL(12, 2) NOT NULL,
    `ventilationCost` DECIMAL(12, 2) NOT NULL,
    `totalMaterialsCost` DECIMAL(12, 2) NOT NULL,
    `laborCost` DECIMAL(12, 2) NOT NULL,
    `removalCost` DECIMAL(12, 2) NOT NULL,
    `totalCost` DECIMAL(12, 2) NOT NULL,
    `gutterPieces` INTEGER NOT NULL,
    `ridgeLength` DECIMAL(10, 2) NOT NULL,
    `complexityScore` INTEGER NOT NULL,
    `complexityLevel` VARCHAR(191) NOT NULL,
    `recommendedMaterial` VARCHAR(191) NULL,
    `optimizationTips` LONGTEXT NULL,
    `notes` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `Project_userId_idx`(`userId`),
    INDEX `Project_status_idx`(`status`),
    INDEX `Project_created_at_idx`(`created_at`),
    INDEX `Project_name_idx`(`projectName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `project` ADD CONSTRAINT `project_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
