-- AlterTable
ALTER TABLE `project` MODIFY `status` ENUM('DRAFT', 'ACTIVE', 'CLIENT_PENDING', 'CONTRACTOR_REVIEWING', 'PROPOSAL_SENT', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', 'REJECTED', 'FOR_CLIENT_REVIEW') NOT NULL DEFAULT 'DRAFT';
